# Generated by Django 5.1.1 on 2024-09-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(default='Access Diamond Bank PLC', max_length=100)),
                ('account_number', models.CharField(default='0063193061', max_length=20)),
                ('recipient_name', models.CharField(default='Abraham Ekene-onwon Hanson', max_length=100)),
            ],
        ),
    ]
